name: 'nextflix'
version: '1.0.0'

profile: 'netflix'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  nextflix:
    # Config indicated by + and applies to all files under models/example/
    +materialized: view
    dim:
      +materialized: table
    fct:
      +materialized: table
    exemple:
      +materialized: view
